name: Publish documentation Website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish documentation to retype branch.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: retypeapp/action-build@v1
        with:
          license: ${{ secrets.RETYPE_LICENSE_KEY }}

      - uses: retypeapp/action-github@v1
        with:
          update-branch: true
